In [2]:
import pandas as pd
import numpy as np
import random

pathFile = "P:/Python - Projetos/Estatística para Ciência de Dados e Machine Learning/Estatística para Ciência de Dados e Machine Learning/Bases de dados"

dataset = pd.read_csv(f"{pathFile}/census.csv")

In [3]:
# Shape do Dataset carregado 
dataset.shape

(32561, 15)

In [4]:
#Primeiras linhas do Dataset carregado  
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [5]:
#Últimas linhas do Dataset carregado  
dataset.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  
32556             0             0             38   United-States   <=50K  
32557             0             0             40   United-States    >50K  
32558             0             0             40   United-States   <=50K  
32559             0             0             20   United-States   <=50K  
32560         15024             0             40   United-States    >50K

In [6]:
df_amostra_aleatoria_simples = dataset.sample(n=100, random_state=1)

In [7]:
df_amostra_aleatoria_simples.shape

(100, 15)

In [8]:
df_amostra_aleatoria_simples.head()

age          workclass  final-weight   education  education-num  \
9646    62   Self-emp-not-inc         26911     7th-8th              4   
709     18            Private        208103        11th              7   
7385    25            Private        102476   Bachelors             13   
16671   33            Private        511517     HS-grad              9   
21932   36            Private        292570        11th              7   

            marital-status          occupation     relationship    race  \
9646               Widowed       Other-service    Not-in-family   White   
709          Never-married       Other-service   Other-relative   White   
7385         Never-married     Farming-fishing        Own-child   White   
16671   Married-civ-spouse      Prof-specialty          Husband   White   
21932        Never-married   Machine-op-inspct        Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
9646    Female             0             0             66   United-States   
709       Male             0             0             25   United-States   
7385      Male         27828             0             50   United-States   
16671     Male             0             0             40   United-States   
21932   Female             0             0             40   United-States   

       income  
9646    <=50K  
709     <=50K  
7385     >50K  
16671   <=50K  
21932   <=50K

In [9]:
def amostragem_aleatoria_simples(dataset, amostras):
    return dataset.sample(n = amostras, random_state=1)

In [10]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [11]:
df_amostra_aleatoria_simples.head()

age          workclass  final-weight   education  education-num  \
9646    62   Self-emp-not-inc         26911     7th-8th              4   
709     18            Private        208103        11th              7   
7385    25            Private        102476   Bachelors             13   
16671   33            Private        511517     HS-grad              9   
21932   36            Private        292570        11th              7   

            marital-status          occupation     relationship    race  \
9646               Widowed       Other-service    Not-in-family   White   
709          Never-married       Other-service   Other-relative   White   
7385         Never-married     Farming-fishing        Own-child   White   
16671   Married-civ-spouse      Prof-specialty          Husband   White   
21932        Never-married   Machine-op-inspct        Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
9646    Female             0             0             66   United-States   
709       Male             0             0             25   United-States   
7385      Male         27828             0             50   United-States   
16671     Male             0             0             40   United-States   
21932   Female             0             0             40   United-States   

       income  
9646    <=50K  
709     <=50K  
7385     >50K  
16671   <=50K  
21932   <=50K

In [12]:
# Amostragem sistemática
len(dataset) // 100

325

In [13]:
# Selecionar um numero aleatório de 0 a 325
random.seed(1)
random.randint(0,325)

68

In [14]:
# Aqui vamos buscar o resultado do Seed (1) somado ao número de amostragem
68+325

393

In [15]:
# Validando os números açeatórios que serão selecionados
393+325

718

In [16]:
# Buscar um range aleatório com base nas amostragens que levantamos anteriormente.
np.arange(68, len(dataset), step=325)


array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [17]:

#Vamos criar uma função para colocar o codigo da amostragem sistemática
def amostragem_sistematica(dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inicio, len(dataset), step = intervalo)
    amostra_sistematica = dataset.iloc[indices]
    return amostra_sistematica

In [18]:
df_amostra_sistematica = amostragem_sistematica(dataset, 100)
df_amostra_sistematica.shape

(100, 15)

In [19]:
df_amostra_sistematica.head()

age      workclass  final-weight      education  education-num  \
68     49   Self-emp-inc        191681   Some-college             10   
393    34      State-gov         98101      Bachelors             13   
718    22        Private        214399   Some-college             10   
1043   44        Private        167005      Bachelors             13   
1368   52        Private        152234        HS-grad              9   

           marital-status        occupation relationship                 race  \
68     Married-civ-spouse   Exec-managerial      Husband                White   
393    Married-civ-spouse   Exec-managerial      Husband                White   
718         Never-married             Sales    Own-child                White   
1043   Married-civ-spouse   Exec-managerial      Husband                White   
1368   Married-civ-spouse   Exec-managerial      Husband   Asian-Pac-Islander   

          sex  capital-gain  capital-loos  hour-per-week  native-country  \
68       Male             0             0             50   United-States   
393      Male          7688             0             45               ?   
718    Female             0             0             15   United-States   
1043     Male          7688             0             60   United-States   
1368     Male         99999             0             40           Japan   

      income  
68      >50K  
393     >50K  
718    <=50K  
1043    >50K  
1368    >50K

In [20]:
len(dataset) // 10

3256

In [21]:
grupos = []
id_grupo = 0 
contagem = 0
#não vai ter uma variável para controlar esse for, ela vai percorrer o dataset pela função iterrows
for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

In [22]:
print(np.unique(grupos))

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# Return counts é usado para contagem dos valores dentro do dataset grupos
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [24]:
np.shape(grupos), dataset.shape


((32561,), (32561, 15))

In [25]:
dataset['grupo'] = grupos

In [26]:
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [27]:
dataset.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  \
32556             0             0             38   United-States   <=50K   
32557             0             0             40   United-States    >50K   
32558             0             0             40   United-States   <=50K   
32559             0             0             20   United-States   <=50K   
32560         15024             0             40   United-States    >50K   

       grupo  
32556      9  
32557      9  
32558      9  
32559      9  
32560      9

In [28]:
random.randint(0, 9)

9

In [29]:
df_agrupamento = dataset[dataset['grupo'] == 7]
df_agrupamento.shape

(3257, 16)

In [30]:
df_agrupamento['grupo'].value_counts()

grupo
7    3257
Name: count, dtype: int64

In [37]:
def amostragem_agrupamento(dataset, numero_grupos):
    intervalo = len(dataset) / numero_grupos

    grupos = []
    id_grupo = 0
    contagem = 0
    for _ in dataset.iterrows():
        grupos.append(id_grupo)
        contagem += 1
        if contagem > intervalo:
            contagem = 0
            id_grupo += 1
    
    dataset['grupo'] = grupos
    random.seed(1)
    grupo_selecionado = random.randint(0, numero_grupos)
    return dataset[dataset['grupo'] == grupo_selecionado]

In [39]:
#Quer dizer que se criarmos 325 datasets, teremos 100.18... registros em cada grupo
len(dataset) / 325

100.1876923076923

In [38]:
df_amostra_agrupamento = amostragem_agrupamento(dataset, 100)
df_amostra_agrupamento.shape, df_amostra_agrupamento['grupo'].value_counts()

((326, 16),
 grupo
 17    326
 Name: count, dtype: int64)

In [42]:
df_amostra_agrupamento.head(5)

age          workclass  final-weight      education  education-num  \
5542   40       Self-emp-inc        169878     Assoc-acdm             12   
5543   44            Private        296728        Masters             14   
5544   33          Local-gov        342458     Assoc-acdm             12   
5545   21          Local-gov         38771   Some-college             10   
5546   35   Self-emp-not-inc        269300      Bachelors             13   

           marital-status        occupation    relationship    race      sex  \
5542   Married-civ-spouse   Exec-managerial            Wife   White   Female   
5543   Married-civ-spouse   Exec-managerial         Husband   White     Male   
5544             Divorced   Protective-serv   Not-in-family   White     Male   
5545        Never-married      Adm-clerical       Own-child   White     Male   
5546        Never-married     Other-service   Not-in-family   Black   Female   

      capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
5542             0             0             40   United-States    >50K     17  
5543             0             0             40   United-States    >50K     17  
5544             0             0             56   United-States   <=50K     17  
5545             0             0             40   United-States   <=50K     17  
5546             0             0             60   United-States   <=50K     17